<?php

return [
    /*
     * Default environment
     */
    'default' => env('SNOWFLAKE_ENV', 'plaw'),

    /*
     * Environment-specific configurations
     */
    'environments' => [
        /*
         * PLAW Environment Configuration
         * Production-like AWS environment
         */
        'plaw' => [
            'account' => 'HAB56998',
            'user' => 'DPAUTOMATIONPLAW',
            'database' => 'DPP_DATA',
            'schema' => 'READER',
            'warehouse' => 'DEFAULT_WH',
            'role' => 'ACCOUNTADMIN',
            'private_key' => '-----BEGIN ENCRYPTED PRIVATE KEY-----
MIIE6TAbBgkqhkiG9w0BBQMwDgQIbpKYKgVo79UCAggABIIEyPn4uP9XY+/UqS5C
5LZYsKq4KTY/Z4Tp8y1hJkzgk3n2VjzIlzMQEBxKPPF0CQJQ6O2w7Nt9XuEVzgYq
Fyu2pDKUkDLV+jNONFwGCNlbvRDExIHkDJo0fSBdmWxoV1EvSEQf+xYY4P7a5aaL
LYuC9y+5yt5nDWTPzQqWgznxY+F7cGmr7NXUe1UYh7xUwLQSMLqKZmNlU/oIDazR
YlJBTXJoYE9r70nNr18Bzu3JN0mThCjZfhPUE8kfHIusmLnCUJWnoCDvLqJslB3a
jjeLFMcQhcYJBJGXU7aPxf2oFQG8jOGqGIqSRPMlVD3kFfR4HrN9vBjVNdXtNM3I
YEp3f2Y2FwkDFPCvfE5ZHwFzwCBPMEhzFJv2iGf9vWdxGDQUQOA3xrKlhL3qhJq2
NYhHaQgPZ1TzECMvWIGIi6HiBMlAOdREMb9ggNEQS8VF8UtqN6C3FeqXZRQ5aYcL
3r9zz2NBl7zvH3OuHqLdwNX+J5y1IpKO1XCQfQY9E4kDQ0K0F1s4vPGZnFGECQS1
GQIIxQO7+5S5wIhp0AuFPU1aWrVaQZVn3nP7kYVCHCMfJ+U6B8Hm3OxX7oF+vY3A
rE8T8gNZ9xWX9DLbQ1YZtYqYJZnWwFDFnQHQC3KdKT7oCf3PhYYD7Sj7F+vXBFNA
bXFOuJY6RhKqBLFQYOBN+0oXhvIkT4vVUaLhPSqE3tGz3OZ1wXPqRqrQxI7DyMlQ
cJQwPQqhKZQxQvJjnRzGPbzLYx9WXDqF9vB9+7nJHGQFnRzNYqT0fFZ9wQMYBJlQ
h2F3YF7FLUzNxQqJYqZFPCCOD7xQ0MvHYFGLQ9JZBLhRQDnFXZLQqBLtYQPFQYqh
9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQ
FLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPF
QYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZ
FLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLt
YQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFP
QDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQ
qBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLh
QxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDn
FZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZx
RqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQ
xQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh
9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQ
FLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPF
QYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZ
FLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLt
YQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFP
QDYZFLYQFL+cGZ07vDsf
-----END ENCRYPTED PRIVATE KEY-----',
            'private_key_passphrase' => 'Qq$D^8)_12',
        ],

        /*
         * LDR Environment Configuration
         * Leader environment
         */
        'ldr' => [
            'account' => 'REB62717',
            'user' => 'DPAUTOMATIONLDR',
            'database' => 'DPP_DATA',
            'schema' => 'READER',
            'warehouse' => 'DEFAULT_WH',
            'role' => 'ACCOUNTADMIN',
            'private_key' => '-----BEGIN ENCRYPTED PRIVATE KEY-----
MIIE6TAbBgkqhkiG9w0BBQMwDgQI1c7KA0KmnNUCAggABIIEyLz3YAjkI7WmDEQF
dMZKcI5W32uLW3sXqYNZjL4aLBHPkK3VD9wDnQBYJGNFQZYGFDzNFPLF1LQYqBQF
nZFQxLhQ3FPQ0YqhDLZFRxQqLhFXFPQDnYZFQYLQFLhQxQDnFZLQqBLtYQPFQYqh
9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQ
FLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPF
QYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZ
FLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLt
YQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFP
QDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQ
qBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLh
QxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDn
FZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZx
RqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQ
xQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh
9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQ
FLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPF
QYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZ
FLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLt
YQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFP
QDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQ
qBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLh
QxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDn
FZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZx
RqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQ
xQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh
9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQ
FLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPF
QYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZ
FLYQFL8gv8xKf1kg
-----END ENCRYPTED PRIVATE KEY-----',
            'private_key_passphrase' => 'Aa@Bq#(*)42',
        ],

        /*
         * LT Environment Configuration
         * Local testing environment
         */
        'lt' => [
            'account' => 'HIB62913',
            'user' => 'DPAUTOMATIONLT',
            'database' => 'DPP_DATA',
            'schema' => 'READER',
            'warehouse' => 'DEFAULT_WH',
            'role' => 'ACCOUNTADMIN',
            'private_key' => '-----BEGIN ENCRYPTED PRIVATE KEY-----
MIIE6TAbBgkqhkiG9w0BBQMwDgQISjtzOBHj++sCAggABIIEyJi/3O66L+eSoQJL
1lJpRlhQzFYFLQDnBYZQxLFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtY
QPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQ
DYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQq
BLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQ
xFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnF
ZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxR
qLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQx
QDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9
LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQF
LhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQ
Yqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZF
LYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtY
QPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQ
DYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQq
BLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQ
xFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnF
ZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxR
qLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQx
QDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9
LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQF
LhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQ
Yqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZF
LYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtY
QPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQ
DYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQq
BLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQ
xFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnF
ZLQqBLtYQPFQYqh9LZxRqLhQxFPQDYZFLYQFLhQxQDnFZLQqBLtYQPFQYqh9LZxR
qLhQxFPQDYZFLYQFL9hpKIKBYmU=
-----END ENCRYPTED PRIVATE KEY-----',
            'private_key_passphrase' => 'Za#F!&8_90',
        ],
    ],
];
